### PR TITLE
Use a modern and maintained Async analyzer

### PR DESCRIPTION
**Pull request by ErikEJ**
~~(and avoid reported issues with older analyzers)~~

I have used this in an ASP.NET Core 3.1/5/6 solution

### CODE REVIEW

**Review by davidkallesen — COMMENTED** [review]
* We also have to rename folder: https://github.com/atc-net/atc-coding-rules/tree/main/documentation/CodeAnalyzersRules/AsyncFixer -> https://github.com/atc-net/atc-coding-rules/tree/main/documentation/CodeAnalyzersRules/MicrosoftVisualStudioThreadingAnalyzers
* Delete folder: https://github.com/atc-net/atc-coding-rules/tree/main/documentation/CodeAnalyzersRules/Asyncify

**Comment by ErikEJ** [comment]
@davidkallesen I have already done that - try:

    gh pr checkout 68 

and have a look

**Review by davidkallesen — APPROVED** [review]

**Comment by LarsSkovslund** [comment]
The suggested new analyzer `Microsoft.VisualStudio.Threading.Analyzers` is target towards running in Visual Studio including the constraints imposed by it. I don't see this as a all around analyzer.

**Comment by davidkallesen** [comment]
After reading [Async code smells and how to track them down with analyzers - Part I](https://cezarypiatek.github.io/post/async-analyzers-p1/#summary) and [Async code smells and how to track them down with analyzers - Part II](https://cezarypiatek.github.io/post/async-analyzers-p2/#summary)
I think [AsyncFixer](https://github.com/semihokur/AsyncFixer) is still relevante... and still not sure how [vs-threading](https://github.com/microsoft/vs-threading) is dependent on Visual Studio

**Comment by ErikEJ** [comment]
@davidkallesen agree - all three analysers are relevant! (I also found your link) - I will update the PR.

**Comment by LarsSkovslund** [comment]
I might have expressed myself wrongly in regards to `Microsoft.VisualStudio.Threading.Analyzers`. What is was trying to say was that the rules enforce in this library are there to govern how you write VS extensions code. Please see [FAQ here](https://github.com/microsoft/vs-threading/blob/main/doc/threading_rules.md#frequently-asked-questions).

**Comment by ErikEJ** [comment]
@LarsSkovslund I do not agree, some of the rules are generally useful, as mentioned in the blog post linked above.

**Comment by LarsSkovslund** [comment]
Yes some of them are useful, but they will conflict with other async rules and/or suggest changes that are not appropriate for most projects unless you write Windows UI code. If we go through them one by one you will see these are target against STA/MTA issues or synchronizing with the UI thread.

@ErikEJ  would it be possible for you to point me in the direction of included rules that is not related to VS internals or UI programming (async void is in this category)?

If the primary use-case for this analyzer is when writing Windows UI code, this should only be included there and not as a general requirement for all project types.

**Comment by ErikEJ** [comment]
@LarsSkovslund Sorry, I thought @davidkallesen had already linked to them above 😊 - https://cezarypiatek.github.io/post/async-analyzers-summary/ - as you can see in the [summary](https://cezarypiatek.github.io/post/async-analyzers-summary/#summary) there are 2-3 rules in the vs-threading rules that are useful. (You can always discuss each, for example VSTHRD200)

**Comment by ErikEJ** [comment]
PR updated

**Comment by ErikEJ** [comment]
Are you waiting for me to do anything here?

**Pull request closed without merging**
